name: 'Create Release Notes'
description: ''
inputs:
  GH_PAT:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        VERSION=$(node -p "require('./package.json').version")
        curl -X POST \
          -H "Authorization: token ${{ inputs.GH_PAT }}" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\": \"v$VERSION\", \"name\": \"v$VERSION\", \"body\": \"Release v$VERSION\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases
      shell: bash