name: 'Trigger Deploy'
description: ''
inputs:
  VERSION:
    required: true
  GH_PAT:
    required: true
  PATH_TO_TERRAFORM_FILE:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        VERSION=${{ inputs.VERSION }}
        
        git clone https://x-access-token:${{ inputs.GH_PAT }}@github.com/tsai-tech/terraform.git
        cd terraform
        
        TARGET_FILE="${{ inputs.PATH_TO_TERRAFORM_FILE }}"

        sed -E -i "s/(version[[:space:]]*=[[:space:]]*\")[^\"]+(\")/\1${VERSION}\2/" "$TARGET_FILE"
        
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add "$TARGET_FILE"
        git commit -m "chore: update ${{ github.repository }} version to ${VERSION}"
        git push
      shell: bash
