name: 'NPM Version Patch'
description: 'Patch version in package.json and commit changes'
inputs:
  GH_PAT:
    required: true
outputs:
  version:
    description: 'Version after patching'
    value: ${{ steps.set-version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - id: set-version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        npm version patch
        git remote set-url origin https://x-access-token:${{ inputs.GH_PAT }}@github.com/${{ github.repository }}.git
        git push origin HEAD:main --follow-tags

        VERSION=$(node -p "require('./package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash