name: 'Build and Release Image'
description: 'Build and push Docker-image, create GitHub Release'
inputs:
  VERSION:
    required: true
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        VERSION=${{ inputs.VERSION }}

        IMAGE_NAME=$(echo "${{ github.repository }}" | tr '/' '-')
        echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USERNAME }}" --password-stdin
        docker build -t ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION .
        docker push ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION
      shell: bash