name: 'Build and Release Image'
description: 'Build and push Docker-image, create GitHub Release'
inputs:
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo "USERNAME: ${{ inputs.DOCKER_USERNAME }}"
        echo "PASSWORD: ${{ inputs.DOCKER_PASSWORD }}"
      shell: bash

    - run: |
        VERSION=$(node -p "require('./package.json').version")
        IMAGE_NAME=$(echo "${{ github.repository }}" | tr '/' '-')
        echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USERNAME }}" --password-stdin
        docker build -t ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION .
        docker push ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION
      shell: bash