name: 'Build and Release Image'
description: 'Build and push Docker-image, create GitHub Release'
inputs:
  GH_PAT:
    required: true
  DOCKER_USERNAME:
    required: true
  DOCKER_PASSWORD:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        VERSION=$(node -p "require('./package.json').version")
        IMAGE_NAME=$(echo "${{ github.repository }}" | tr '/' '-')
        echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USERNAME }}" --password-stdin
        docker build -t ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION .
        docker push ${{ inputs.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION
        curl -X POST \
          -H "Authorization: token ${{ inputs.GH_PAT }}" \
          -H "Content-Type: application/json" \
          -d "{\"tag_name\": \"v$VERSION\", \"name\": \"v$VERSION\", \"body\": \"Release v$VERSION\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases
      shell: bash