name: Create Release Image
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      PATH_TO_TERRAFORM_FILE:
        required: true
      PREFIX:
        required: true
jobs:
  npm-version-patch:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.patch.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: tsai-tech/workflows/.github/actions/npm-version-patch@main
        id: patch
        with:
          GH_PAT: ${{ secrets.GH_PAT }}

  build:
    runs-on: ubuntu-latest
    needs: npm-version-patch
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install deps and build
        run: |
          npm ci
          npm run build

      - uses: tsai-tech/workflows/.github/actions/build-release-image@main
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ needs.npm-version-patch.outputs.version }}

  create-release-notes:
    runs-on: ubuntu-latest
    needs: npm-version-patch
    steps:
      - uses: tsai-tech/workflows/.github/actions/create-release-notes@main
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          VERSION: ${{ needs.npm-version-patch.outputs.version }}

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: [npm-version-patch, build]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: tsai-tech/workflows/.github/actions/trigger-deploy@main
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PATH_TO_TERRAFORM_FILE: ${{ secrets.PATH_TO_TERRAFORM_FILE }}
          VERSION: ${{ needs.npm-version-patch.outputs.version }}
          PREFIX: ${{ secrets.PREFIX }}